ProjectsControl/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace ProjectsControl.Models
{
    public class Employee
    {
        [Key]
        [Required]
        public string EmployeeId { get; set; }
        public int EmployeeDNI { get; set; }

        [Required]
        [MinLength(10)]
        [MaxLength(60)]
        public string Name { get; set; }
        [Required(ErrorMessage ="Dato Requerido")]
        public string Position { get; set; }
        [Required(ErrorMessage = "Dato Requerido")]
        public DateTime DateofHiring { get; set; }
        [Required(ErrorMessage = "Dato Requerido")]
        public DateTime DateOfBirth { get; set; }
        public DateTime DateOfFired { get; set; }
        public bool IsActive { get; set; }
        [Required(ErrorMessage = "Dato Requerido")]
        public int MobileNumber { get; set; }
        [Required(ErrorMessage = "Dato Requerido")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Dato Requerido")]
        public float Salary { get; set; }


        public ICollection<ExtraHour> ExtraHours { get; set; }
        public ICollection<Asistance> Asistances { get; set; } 
        public ICollection<Action> Actions { get; set; }
        public ICollection<Project> Projects { get; set; }
        public ICollection<Salary> Salaries { get; set; }
    }
   
}

ProjectsControl/Controllers/ActionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectsControl.Models;
using Microsoft.AspNetCore.Authorization;
using Action = ProjectsControl.Models.Action;

namespace ProjectsControl.Controllers
{
    [Authorize]
    public class ActionsController : Controller
    {
        private readonly DBProjectContext _context;

        public ActionsController(DBProjectContext context)
        {
            _context = context;
        }
        #region View Methods
        // GET: Actions
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var dBProjectContext = _context.Actions.Include(a => a.Employee);
            return View(await dBProjectContext.ToListAsync());
        }

        // GET: Actions/Details/5
        [Authorize(Roles ="Admin,Editor,Lector")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _context.Actions
                .Include(a => a.Employee)
                .FirstOrDefaultAsync(m => m.ActionId == id);
            if (action == null)
            {
                return NotFound();
            }

            return View(action);
        }

        public async Task<IActionResult> PrintableView(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _context.Actions
                .Include(a => a.Employee)
                .FirstOrDefaultAsync(m => m.ActionId == id);
            if (action == null)
            {
                return NotFound();
            }

            return View(action);
        }

        // GET: Actions/Create
        [Authorize(Roles = "Admin,Editor")]
        public IActionResult Create()
        {
            ViewBag.Employees = (from empl in _context.Employees select empl).Where(E => E.IsActive == true).ToList();
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeId");
            return View();
        }

        // POST: Actions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Editor")]
        public async Task<IActionResult> Create([Bind("ActionId,Title,DateOfCreation,Author,TypeOfAction,Description,IsActive,EmployeeId")] Action oaction)
        {
            if (ModelState.IsValid)
            {
                _context.Add(oaction);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Employees = (from empl in _context.Employees select empl).Where(E => E.IsActive == true).ToList();
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeId", oaction.EmployeeId);
            return View(oaction);
        }

        // GET: Actions/Edit/5
        [Authorize(Roles = "Admin,Editor")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _context.Actions.FindAsync(id);
            if (action == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeId", action.EmployeeId);
            return View(action);
        }

        // POST: Actions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,Editor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ActionId,Title,DateOfCreation,Author,TypeOfAction,Description,IsActive,EmployeeId")] Action oaction)
        {
            if (id != oaction.ActionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(oaction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActionExists(oaction.ActionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeId", oaction.EmployeeId);
            return View(oaction);
        }

        // GET: Actions/Delete/5
        [Authorize(Roles = "Admin,Editor")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _context.Actions
                .Include(a => a.Employee)
                .FirstOrDefaultAsync(m => m.ActionId == id);
            if (action == null)
            {
                return NotFound();
            }

            return View(action);
        }

        // POST: Actions/Delete/5
        [Authorize(Roles = "Admin,Editor")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var action = await _context.Actions.FindAsync(id);
            _context.Actions.Remove(action);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        #endregion

        #region Internal Methods

        private bool ActionExists(string id)
        {
            return _context.Actions.Any(e => e.ActionId == id);
        }

        #endregion


    }
}

ProjectsControl/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectsControl.Models;
using Microsoft.AspNetCore.Authorization;


namespace ProjectsControl.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        private readonly DBProjectContext _context;

        public EmployeesController(DBProjectContext context)
        {
            _context = context;
        }

        #region View Methods

        // GET: Employees
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            
            return View(await _context.Employees.ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var Salary = GetActiveSalary(id);
            ViewBag.ActiveSalary = Salary;
            var actions = (from act in _context.Actions select act).Where(E => E.EmployeeId == id).OrderByDescending(E => E.DateOfCreation).ToList();
            ViewBag.actions = actions;
            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        [Authorize(Roles = "Admin,Editor")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,Editor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeeId,EmployeeDNI,Name,Position,DateOfBirth,DateofHiring,DateOfFired,IsActive,MobileNumber,Email,Salay")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        [Authorize(Roles = "Admin,Editor")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,Editor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("EmployeeId,ProjectName,DateofHiring,Position")] Employee employee)
        {
            if (id != employee.EmployeeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmployeeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        [Authorize(Roles = "Admin,Editor")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [Authorize(Roles ="Admin,Editor")]        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        #endregion
        #region Internal Methods
        [AllowAnonymous]
        private bool EmployeeExists(string id)
        {
            return _context.Employees.Any(e => e.EmployeeId == id);
        }
        private Salary GetActiveSalary(string id = null)
        {
            if (id != null)
            {
                var tmpResults = _context.Salary.FirstOrDefault(S => S.EmployeeId == id && S.isActive);
                return tmpResults;
            }
            else
            {
                return null;
            }
        }

        #endregion
    }
}

ProjectsControl/Views/Employees/Create.cshtml
@model ProjectsControl.Models.Employee

@{
    ViewData["Title"] = "Crear Empleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Creación</h1>

<h4>Registro de Empleado</h4>
<hr />
<div class="container">
    <div class="row align-items-start">
        <!-- FORM-->
        <div class="col">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label">Id de Referencia Interno</label>
                    <input asp-for="EmployeeId" class="form-control" value="@Guid.NewGuid().ToString()" readonly />
                    <span asp-validation-for="EmployeeId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Cedula</label>
                    <input asp-for="EmployeeDNI" class="form-control" />
                    <span asp-validation-for="EmployeeDNI" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Nombre</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Cargo</label>
                    <select asp-for="Position" class="form-control">
                        <option value="Vendedor">Vendedor</option>
                        <option value="Asistente Ventas">Asistente Ventas</option>
                        <option value="Ayudante">Ayudante</option>
                        <option value="Tecnico">Tecnico</option>
                        <option value="Ingeniero">Ingeniero</option>
                        <option value="Asistente Ingenieria">Asistente Ingenieria</option>
                        <option value="Asistente administrativo">Asistente administrativo</option>
                        <option value="Contador">Contador</option>
                    </select>
                    <span asp-validation-for="Position" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Fecha de nacimiento</label>
                    <input asp-for="DateOfBirth" class="form-control" />
                    <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Fecha de Contratación</label>
                    <input asp-for="DateofHiring" class="form-control" />
                    <span asp-validation-for="DateofHiring" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Fecha de despido</label>
                    <input asp-for="DateOfFired" class="form-control" />
                    <span asp-validation-for="DateOfFired" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Esta activo</label>
                    <input asp-for="IsActive" class="form-control" />
                    <span asp-validation-for="IsActive" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Numero de Telefono</label>
                    <input asp-for="MobileNumber" class="form-control" />
                    <span asp-validation-for="MobileNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Correo</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                </div>
            </form>
        </div>
        <!-- INFORMATION -->
        <div class="col-4 container m-2">
            <div class="col">
                <div class="row m-3">
                    <div class="card">
                        <div class="card-body">
                            Esta sección permite el ingreso de un nuevo empleado en la base de datos.  <b>antes de realizar la inserción, verifique que posea todos los datos necesarios del empleado </b>
                        </div>
                    </div>
                </div>
                <div class="row m-3">
                    <div class="card">
                        <div class="card-body">
                            <b>Verifique que este empleado no se encuentre previamente registrado en el sistema.</b>
                        </div>
                    </div>
                </div>
                <div class="row m-3">
                    <div class="card">
                        <div class="card-body">
                            <b>Esta activo</b> indique que el empleado se encuentra activo, de esta forma estará disponible para seleccionar dentro del sistema. Una vez el empleado no sea parte de la organización, indique que ya no se encuentra activo.
                        </div>
                    </div>
                </div>
                <div class="row m-3">
                    <div class="card">
                        <div class="card-body">
                            <b>Fecha despido:</b> Este dato solamente es relevante al momento de una renuncia o despido. Para efectos de ingreso, este dato será el mismo que la fecha de contratación.
                        </div>
                    </div>
                </div>              
            </div>
        </div>
    </div>
</div>


<div>
    <a asp-action="Index" class="btn btn-secondary">Volver a Index</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

ProjectsControl/Views/Employees/Delete.cshtml
@model ProjectsControl.Models.Employee

@{
    ViewData["Title"] = $"Delete {Model.Name}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar este registro</h1>

<h3>¿Está seguro que desea eliminar este registro?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nombre
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Fecha de Contratación
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateofHiring)
        </dd>
        <dt class = "col-sm-2">
            Posición
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EmployeeId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary" >Volver Atrás</a>
    </form>
</div>

ProjectsControl/Views/Employees/Details.cshtml
@model ProjectsControl.Models.Employee

@{
    ViewData["Title"] = $"Detalles {Model.Name}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalles</h1>


<div class="border rounded m-2 p-2">
    <div class="d-flex flex-row justify-content-between">
        <h4>Empleado</h4>
        <div>
            <a asp-action="Edit" asp-route-id="@Model.EmployeeId" class="btn btn-primary">Editar</a> |
            <a asp-action="Index" class="btn btn-secondary">Volver Atrás</a>
        </div>
    </div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Nombre
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Fecha de Nacimiento
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth.Date)
        </dd>
        <dt class="col-sm-2">
            Fecha de Contratación
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateofHiring)
        </dd>
        <dt class="col-sm-2">
            Posición
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class="col-sm-2">
            Correo
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            Telefono
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MobileNumber)
        </dd>
        <dt class="col-sm-2">
            Correo
        </dt>
        <dd class="col-sm-10">
            @if (Model.IsActive)
            {
                <label>Empleado Activo</label>
            }
            else
            {
                <label>Empleado Desactivado</label>
            }
        </dd>
    </dl>
</div>
<div class="border rounded m-2 p-2">
    @if (ViewBag.ActiveSalary != null)
    {
        <div class="d-flex flex-row justify-content-between">
            <h5>
                Salario Activo
            </h5>
            <div>
                <a asp-controller="Salaries" asp-action="CreateByEmployee" asp-route-id="@Model.EmployeeId"
                class="btn btn-success">Cambiar Salario</a> |
                <a asp-controller="Salaries" asp-action="ListSalariesByEmployee" asp-route-id="@Model.EmployeeId"
                class="btn btn-primary">Historial de Salarios</a>
            </div>
        </div>
        <hr />
        <div>
            <label>
                <b>Monto</b>
            </label>
            <label>
                @ViewBag.ActiveSalary.SalaryAmount -(Salario en colones)
            </label>
        </div>
        <div>
            <label>
                <b>Fecha de Aplicación</b>
            </label>
            <label>
                @ViewBag.ActiveSalary.DayOfApplication.ToShortDateString()
            </label>
        </div>
    }
    else
    {
        <div class="d-flex flex-row justify-content-between">
            <h5>
                Salario no registrado
            </h5>
            <div>
                <a asp-controller="Salaries" asp-action="CreateByEmployee" asp-route-id="@Model.EmployeeId"
                class="btn btn-success">Cambiar Salario</a> |
            </div>
        </div>
    }
</div>

<div class="border rounded m-2 p-2">
    <h2>
        Historial de Acciones de Personal Registradas
    </h2>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    Titulo
                </th>
                <th>
                    Fecha Creación
                </th>
                <th>
                    Autor
                </th>
                <th>
                    Tipo
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.actions)
            {
                <tr>
                    <td>
                        @item.Title
                    </td>
                    <td>
                        @item.DateOfCreation
                    </td>
                    <td>
                        @item.Author
                    </td>
                    <td>
                        @item.TypeOfAction
                    </td>
                    <td>
                        <a asp-controller="Actions" asp-action="Edit" asp-route-id="@item.ActionId"
                        class="btn btn-primary">Editar</a>
                    </td>
                    <td>
                        <a asp-controller="Actions" asp-action="Details" asp-route-id="@item.ActionId"
                        class="btn btn-info">Detalles</a>
                    </td>
                    <td>
                        <a asp-controller="Actions" asp-action="Delete" asp-route-id="@item.ActionId"
                        class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

ProjectsControl/Views/Employees/Edit.cshtml
@model ProjectsControl.Models.Employee

@{
    ViewData["Title"] = $"Editar {Model.Name}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Empleado</h4>
<hr />
<div >
    <div >
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EmployeeId" />
            <div class="form-group">
                <label class="control-label">Cedula</label>
                <input asp-for="EmployeeDNI" class="form-control" />
                <span asp-validation-for="EmployeeDNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Nombre</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Cargo</label>
                <select asp-for="Position" class="form-control">
                    <option value="Vendedor">Vendedor</option>
                    <option value="Asistente Ventas">Asistente Ventas</option>
                    <option value="Ayudante">Ayudante</option>
                    <option value="Tecnico">Tecnico</option>
                    <option value="Ingeniero">Ingeniero</option>
                    <option value="Asistente Ingenieria">Asistente Ingenieria</option>
                    <option value="Asistente administrativo">Asistente administrativo</option>
                    <option value="Contador">Contador</option>
                </select>
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Fecha de nacimiento</label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Fecha de Contratación</label>
                <input asp-for="DateofHiring" class="form-control" />
                <span asp-validation-for="DateofHiring" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Fecha de despido</label>
                <input asp-for="DateOfFired" class="form-control" />
                <span asp-validation-for="DateOfFired" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">ESta activo</label>
                <input asp-for="IsActive" class="form-control" />
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Numero de Telefono</label>
                <input asp-for="MobileNumber" class="form-control" />
                <span asp-validation-for="MobileNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Correo</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}