ProjectsControl/Models/Bill.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace ProjectsControl.Models
{
    public class Bill
    {
        [Key]
        [Required]
        public string BillId { get; set; }
        [Required]
        public int NumberOfBill { get; set; }
        [Required]
        public DateTime DateOfCreation { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public float Amount { get; set; }
        public string Currency { get; set; }
        public string Notes { get;set; }


        public string ProjectId { get; set; }
        public Project Project { get; set; }
    }
}

ProjectsControl/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectsControl.Models;
using Microsoft.AspNetCore.Authorization;
namespace ProjectsControl.Controllers
{
    [Authorize]
    public class BillsController : Controller
    {
        private readonly DBProjectContext _context;

        public BillsController(DBProjectContext context)
        {
            _context = context;
        }


        #region Views Methods
        // GET: Bills
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var dBProjectContext = _context.Bill.Include(b => b.Project);
            return View(await dBProjectContext.ToListAsync());
        }

        // GET: Bills/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .Include(b => b.Project)
                .FirstOrDefaultAsync(m => m.BillId == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // GET: Bills/Create
        [Authorize(Roles = "Admin,Editor")]
        public IActionResult Create()
        {            
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectId");
            ViewBag.Projects = (from proj in _context.Projects select proj).Where(P => P.IsOver == false).OrderBy(P=>P.NumberOfProject);
            return View();
        }

        // POST: Bills/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,Editor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BillId,NumberOfBill,DateOfCreation,Author,Amount,ProjectId")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bill);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectId", bill.ProjectId);
            return View(bill);
        }

        // GET: Bills/Edit/5
        [Authorize(Roles = "Admin,Editor")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill.FindAsync(id);
            if (bill == null)
            {
                return NotFound();
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectId", bill.ProjectId);
            return View(bill);
        }

        // POST: Bills/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,Editor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("BillId,NumberOfBill,DateOfCreation,Author,Amount,ProjectId")] Bill bill)
        {
            if (id != bill.BillId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bill);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillExists(bill.BillId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectId", bill.ProjectId);
            return View(bill);
        }

        // GET: Bills/Delete/5
        [Authorize(Roles = "Admin,Editor")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .Include(b => b.Project)
                .FirstOrDefaultAsync(m => m.BillId == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // POST: Bills/Delete/5
        [Authorize(Roles = "Admin,Editor")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var bill = await _context.Bill.FindAsync(id);
            _context.Bill.Remove(bill);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Search(string IdToSearch=null,string AuthorToSearch = null, string ProjectIdToSearch=null)
        {
            List<Bill> Bills = new List<Bill>();
            if ((IdToSearch != null) || (AuthorToSearch != null) || (ProjectIdToSearch != null))
            {
                Bills = Consult(IdToSearch, AuthorToSearch,ProjectIdToSearch);
                if(Bills.Count > 0)
                {
                    ViewBag.Message = "";
                    return View(Bills);
                }
                else
                {
                    ViewBag.Message = "No hay coincidencias";
                    return View(Bills);
                }
            }
            return View(new List<Bill>());
        }

        #endregion

        #region Internal Methods
        [AllowAnonymous]
        private bool BillExists(string id)
        {
            return _context.Bill.Any(e => e.BillId == id);
        }
        [AllowAnonymous]
        public List<Bill> Consult(string IdToSearch = null, string AuthorToSearch = null, string ProjectIdToSearch = null)
        {
            if ((IdToSearch != null) && (AuthorToSearch != null) && (ProjectIdToSearch != null))
            {
                return _context.Bill.FromSqlInterpolated($@"SELECT * FROM Bill
                                                            WHERE	( BillId LIKE CONCAT('%',{IdToSearch},'%') )
                                                            AND		( Author LIKE CONCAT('%',{AuthorToSearch},'%') )
                                                            AND		( ProjectId LIKE CONCAT('%',{ProjectIdToSearch},'%') )").ToList();
            }
            else if ((IdToSearch != null) && (AuthorToSearch != null) && (ProjectIdToSearch == null))
            {
                return _context.Bill.FromSqlInterpolated($@"SELECT * FROM Bill
                                                            WHERE	( BillId LIKE CONCAT('%',{IdToSearch},'%') )
                                                            AND		( Author LIKE CONCAT('%',{AuthorToSearch},'%') )").ToList();
            }
            else if ((IdToSearch != null) && (AuthorToSearch == null) && (ProjectIdToSearch == null))
            {
                return _context.Bill.FromSqlInterpolated($@"SELECT * FROM Bill
                                                            WHERE	( BillId LIKE CONCAT('%',{IdToSearch},'%') )").ToList();
            }
            else if ((IdToSearch == null) && (AuthorToSearch != null) && (ProjectIdToSearch != null))
            {
                return _context.Bill.FromSqlInterpolated($@"SELECT * FROM Bill
                                                            WHERE	( Author LIKE CONCAT('%',{AuthorToSearch},'%') )
                                                            AND		( ProjectId LIKE CONCAT('%',{ProjectIdToSearch},'%') )").ToList();
            }
            else if ((IdToSearch == null) && (AuthorToSearch == null) && (ProjectIdToSearch != null))
            {
                return _context.Bill.FromSqlInterpolated($@"SELECT * FROM Bill
                                                            WHERE	( ProjectId LIKE CONCAT('%',{ProjectIdToSearch},'%') )").ToList();
            }
            else if ((IdToSearch == null) && (AuthorToSearch != null) && (ProjectIdToSearch == null))
            {
                return _context.Bill.FromSqlInterpolated($@"SELECT * FROM Bill
                                                            WHERE	( Author LIKE CONCAT('%',{AuthorToSearch},'%'))").ToList();
            }
            else
            {
                return (new List<Bill>());
            }
        }
        #endregion
    }
}

ProjectsControl/Views/Bills/Create.cshtml
@model ProjectsControl.Models.Bill

@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear</h1>

<h4>Factura</h4>
<hr />





<div class="container">
    <div class="row align-items-start">
        <!-- FORM-->
        <div class="col">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label class="control-label">Id de Factura</label>
                        <input asp-for="BillId" class="form-control" value="@Guid.NewGuid().ToString()" readonly />
                        <span asp-validation-for="BillId" class="text-danger"></span>
                    </div>
                    <div class="col-sm-6">
                        <label class="control-label">Numero de Factura</label>
                        <input asp-for="NumberOfBill" class="form-control" />
                        <span asp-validation-for="NumberOfBill" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label class="control-label">Fecha de Creación</label>
                        <input asp-for="DateOfCreation" class="form-control" />
                        <span asp-validation-for="DateOfCreation" class="text-danger"></span>
                    </div>
                    <div class="col-sm-6">
                        <label class="control-label">Autor</label>
                        <input asp-for="Author" class="form-control" />
                        <span asp-validation-for="Author" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label class="control-label">Monto</label>
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                    <div class="col-sm-6">
                        <label class="control-label">Id de Proyecto</label>
                        <select asp-for="ProjectId" class="form-control">
                            @foreach (Project i in ViewBag.Projects)
                            {
                                <option value="@i.ProjectId">N°-@i.NumberOfProject - @i.ProjectName</option>
                            }
                        </select>
                    </div>
                </div>
                <input type="submit" value="Crear" class="btn btn-primary" />
            </form>
        </div>
        <!-- INFORMATION -->
        <div class="col-4 container m-2">
            <div class="col">
                <div class="row m-3">
                    <div class="card">
                        <div class="card-body">
                            Ingrese la información correspondiente a las facturas asociadas al proyecto en cuestión.
                        </div>
                    </div>
                </div>
                <div class="row m-3">
                    <div class="card">
                        <div class="card-body">
                            El número de factura corresponde al consecutivo del mismo, si no posee introduzca un 0
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div>
    <a asp-action="Index" class="btn btn-secondary">Volver Atrás</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectsControl/Views/Bills/Delete.cshtml
@model ProjectsControl.Models.Bill

@{
    ViewData["Title"] = "Borrar Factura";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Borrar Factura</h1>

<h3>¿Esta seguro que desea eliminar esta factura?</h3>
<div>
    <h4>Datos de Factura</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Numero
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfBill)
        </dd>
        <dt class = "col-sm-2">
            Fecha Creación
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfCreation)
        </dd>
        <dt class = "col-sm-2">
            Autor
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            Monto
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            Proyecto
        </dt>
        <dd class = "col-sm-10">
            N° @Model.Project.NumberOfProject - @Model.Project.ProjectName
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BillId" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Volver Atrás</a>
    </form>
</div>

ProjectsControl/Views/Bills/Details.cshtml
@model ProjectsControl.Models.Bill

@{
    ViewData["Title"] = "Detalles de la Factura";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalles de Facturación</h1>

<div>
    <h4>Factura</h4>
    <hr />
    <dl >
        <dt class = "col-sm-2">
            Numero de Factura
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfBill)
        </dd>
        <dt class = "col-sm-2">
            Fecha de Creación
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfCreation)
        </dd>
        <dt class = "col-sm-2">
            Autor
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            Monto
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            Proyecto
        </dt>
        <dd class = "col-sm-10">
            N° @Model.Project.NumberOfProject - @Model.Project.ProjectName
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BillId" class="btn btn-primary">Editar</a> |    
</div>

ProjectsControl/Views/Bills/Edit.cshtml
@model ProjectsControl.Models.Bill

@{
    ViewData["Title"] = $"Editar Factura {Model.NumberOfBill}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Factura</h4>
<hr />
<div >
    <div >
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BillId" />
            <div class="form-group">
                <label  class="control-label">Numero de Factura</label>
                <input asp-for="NumberOfBill" class="form-control" />
                <span asp-validation-for="NumberOfBill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Fecha de Creación</label>
                <input asp-for="DateOfCreation" class="form-control" />
                <span asp-validation-for="DateOfCreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Autor</label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Monto</label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Id de Proyecto</label>
                <select asp-for="ProjectId" class="form-control" asp-items="ViewBag.ProjectId"></select>
                <span asp-validation-for="ProjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectsControl/Views/Bills/Index.cshtml
@model IEnumerable<ProjectsControl.Models.Bill>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Lista de Facturación de Proyectos</h1>

<p>
    <a asp-action="Create">Registrar nueva factura</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Numero de Factura
            </th>
            <th>
                Fecha de Creación
            </th>
            <th>
                Autor
            </th>
            <th>
                Monto
            </th>
            <th>
                Id de Proyecto
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfBill)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfCreation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.ProjectId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BillId" class="btn btn-primary">Editar</a> 
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.BillId" class="btn btn-info">Detalles</a> 
            </td>
            <td>               
                <a asp-action="Delete" asp-route-id="@item.BillId" class="btn btn-danger">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>

ProjectsControl/Views/Bills/Search.cshtml
@model IEnumerable<ProjectsControl.Models.Bill>

@{
    ViewData["Title"] = "Busqueda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Lista de Facturación de proyectos</h1>

<div>
 <a asp-controller="Bills" asp-action="Index">Listar Facturas</a>
</div>

<form asp-controller="Bills" asp-action="Search" method="get">
    <div class="form-group row">
        <div class="col">
            <input style="background-color: #f5f5f5;" type="text" name="IdToSearch" class="rounded form-control" placeholder="Id de Referencia" />
        </div>
        <div class="col">
            <input style="background-color: #f5f5f5;" type="text" name="AuthorToSearch" class="rounded form-control" placeholder="Autor" />
        </div>
        <div class="col">
            <select style="background-color: #f5f5f5;" name="ProjectIdToSearch" class=" rounded form-control">
                <option value="">Proyecto</option>
            </select>
        </div>
        <div class="col">
            <input type="submit" value="Buscar" class="btn btn-light " />
        </div>
    </div>
</form>
    


    
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfBill)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfCreation)
            </th> 
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfBill)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfCreation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BillId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BillId">Details</a> |
                <a class="text-danger" asp-action="Delete" asp-route-id="@item.BillId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>